### PR TITLE
adding secrets file upload

### PR DESCRIPTION
**Pull request by Oribracha**
adding a simple option for uploading a secret text file into the secrets "textarea" and downloading it as a secret file on the receiver side.

### CODE REVIEW

**Comment by 564456** [comment]
fa36b647

**Comment by 564456** [comment]
https://onetimesecret.com/secret/acgudm7ur632qfni5

**Comment by isaija** [comment]
9rsO!nMPehD7

**Comment by isaija** [comment]
роза и соня

**Comment by isaija** [comment]
fa36b64

**Comment by delano** [comment]
I'll be closing this one up unfortunately. Not implementing file support was and is an intentional design choice. Depending on the filetype, it's very easy to accidentally share sensitive information (PDFs, spreadsheets, images of course) without realizing it. We could add support for stripping that stuff out for common types, but we can't guarantee that a file is totally safe to share. 

Our recommendation is still to upload the file using a service you trust, then create a secret with the shareable link. Why do that? Because you can share the secret without revealing where you store files and the exact path to get to one.

Also, what was going on with this thread??

**Pull request closed without merging**
