### PR TITLE
Improve Russian translation

### PR DESCRIPTION
**Pull request by ivan-compucorp**
## Overview
This PR improves translation to Russian language. Many strings were literally translated, hence it was not sound good for native Russian speakers. Maybe not all of them are perfect now, but anyway it sounds much better now.

## Comment
I could also provide translation to some strings that are not translated yet, but localisation file miss them. So it would be possible to do when [issue #138](https://github.com/onetimesecret/onetimesecret/issues/138) would be resolved.

### CODE REVIEW

**Comment by ivan-compucorp** [comment]
@delano could you review?

**Comment by ivan-compucorp** [comment]
@rugk, @chelnak, @kozmic, @webninjasi, @utter-step maybe you guys could review? :)
Is this project still maintained?

**Comment by rugk** [comment]
No I cannot. I don't speak Russian. ANd even if, I could not merge it… :upside_down_face: 

Regarding maintenance, it looks quite abandoned. I've opened an issue about that: https://github.com/onetimesecret/onetimesecret/issues/141

**Comment by delano** [comment]
Thanks @ivan-compucorp, yep still maintained. Just busy so thanks for pinging again. 

If you'd like credit on the site, add you details at the top of list in the contributions template and push to this branch. Otherwise let me know and I'll go ahead and merge now. The changes will be included in the next release.

**Comment by ivan-compucorp** [comment]
@delano could you point me the correct file? I've added myself to `translations.mustache`, but I guess there is some other file where I should add myself to the top of the list as you suggested?

**Comment by delano** [comment]
Ah, sorry I wasn't clear. I meant to say the list of contributors so yep, good to go. Thanks for helping make OTS better.

**Pull request merged**
