### PR TITLE
Update FR translation

### PR DESCRIPTION
**Pull request by netagence**
Suggested FR translation improvements by a native speaker.

### CODE REVIEW

**Comment by netagence** [comment]
Improving French sentences.

**Comment by delano** [comment]
Thanks for making One-Time Secret better! This will be in the next release.

**Comment by delano** [comment]
The updated french translation is now live: https://onetimesecret.com/?locale=fr

Let me know if you would like to change the name or link on the thank you page:
https://onetimesecret.com/translations

**Comment by netagence** [comment]
Hi,

Sounds good - the page does not display my translation yet though ?

Best.

**Comment by fr-laurentn** [comment]
Hi, 

I see that @netagence and I had the same idea at the same time (@delano I sent you a translation file by e-mail, did you received it?). 

Anyway, thanks for the quick release. 
However, like @netagence, I can't see the new translations.

Thanks,

**Comment by delano** [comment]
Thanks for following up guys. The updated translation should be working now:
https://onetimesecret.com/?locale=fr

@fr-laurentn I hadn't seen your email when I did the previous update. Funny that you both had the same thought at the same time. I went ahead and added you to the translation page as well.

**Comment by netagence** [comment]
Confirmed to work now. Not pure chance, Laurent pointed at your nice tool and underlined the FR translation could be improved, which I realized was in GitHub so could be worked on, and I started doing so on a break at work failing to check if he'd do the same. Anyway mine may need polishing up so we'll both contribute in the end I guess. Thanks to both of you.

**Comment by fr-laurentn** [comment]
@delano It works like a charm. Thanks for the credits, I appreciate.

**Pull request merged**
