### PR TITLE
Added Italian translation 

### PR DESCRIPTION
**Pull request by Fastbyte01**
Added the italian translation

### CODE REVIEW

**Comment by delano** [comment]
Thank you! This will be in the next release.

**Comment by delano** [comment]
Now live: https://onetimesecret.com/?locale=it_IT

Let me know what name/link you would like on the translations page (or submit a PR):
https://onetimesecret.com/translations

**Comment by Fastbyte01** [comment]
You can use Giuseppe Pignataro (fastbyte01)

Il 24 Nov 2017 02:13, "Delano Mandelbaum" <notifications@github.com> ha
scritto:

**Comment by delano** [comment]
Done and done. Thanks for helping make One-Time secret better.

**Pull request merged**
