### PR TITLE
bumped ruby base image to 3.3 bookworm

### PR DESCRIPTION
**Pull request by terminaldweller**
bumped the ruby version in the Dockerfile to `3.3`.
solves #278.

### CODE REVIEW

**Comment by eric-glb** [comment]
Indeed it solves #278 (the `docker build` finishes), but #137, #199, #266 and #275 still prevent application to run (or may I have missed something?).

**Comment by vipulwairagade** [comment]
@eric-glb is right. I bumped the Ruby version in Dockerfile but container throws error. Do we have solution for this, a quick fix maybe ? @onetimesecret 

image
image

Error from container 

image

**Comment by delano** [comment]
Thanks folks. I've merged this in to the ruby 2.6 branch. The `develop` branch for Ruby 3+ has been updated as well as part of PR #312 (Update Docker and Docker Compose config).

**Comment by delano** [comment]
> Indeed it solves #278 (the `docker build` finishes), but #137, #199, #266 and #275 still prevent application to run (or may I have missed something?).

@eric-glb Thanks so much for taking the time to list these and generally keeping up with this issue.

**Comment by eric-glb** [comment]
Glad to help, but that's nothing compared to your work. Thanks for sharing this tool!

**Pull request merged**
