### PR TITLE
Bulgarian Translation

### PR DESCRIPTION
**Pull request by Byalk**

### CODE REVIEW

**Comment by delano** [comment]
This is great. Thank you for helping make One-Time Secret better!

**Comment by delano** [comment]
This is now live:
https://onetimesecret.com/?locale=bg

I forgot to ask before, what name and link would like me to include for the thank you:
https://onetimesecret.com/translations

**Comment by Byalk** [comment]
Name: Byalk and link to my GitHub :)

**Comment by delano** [comment]
Done and done

**Pull request merged**
